version: "3.8"
services:
  cakehouse-db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: cakehouse-database
  
  cakehouse-backend:
    image: cakehouse-backend:latest
    environment:
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_DIALECT=$DATABASE_DIALECT
    ports:
      - 8080:8080
    depends_on:
      - cakehouse-db
    container_name: cakehouse-backend

  cakehouse-frontend:
    image: cakehouse-frontend:latest
    environment: