spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cake_house?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: SECRET
    password: SECRET
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    drop-first: true
    
notification:
  email: SECRET
  password: SECRET
    
test:
  email: SECRET
  password: SECRET
        